version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    command: ["./startup.sh"] # Use the startup script to start the app and services

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_HOST=redis
    command: ["celery", "-A", "app.celery", "worker", "--loglevel=info"]
    depends_on:
      - redis
